//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Busqueda de Guia Remision&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;454&quot; height=&quot;298&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/d [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string BusGuiaRem {
            get {
                return ResourceManager.GetString("BusGuiaRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;2000060004&quot; FormType=&quot;2000060004&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Control Guia de Transporte&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;715&quot; height=&quot;456&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;MSS_CGPT&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action ty [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ControlGuia {
            get {
                return ResourceManager.GetString("ControlGuia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconoModulo {
            get {
                object obj = ResourceManager.GetObject("IconoModulo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Maestro de Autorizacion&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;425&quot; height=&quot;166&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;MSS_MAUT&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot;&gt;
        ///         [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string MAutorizacion {
            get {
                return ResourceManager.GetString("MAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon mss {
            get {
                object obj = ResourceManager.GetObject("mss", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;&quot; title=&quot;Maestro de Transportistas&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;293&quot; height=&quot;163&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;MSS_MTRA&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot;&gt;
        ///       [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string MTransportista {
            get {
                return ResourceManager.GetString("MTransportista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;2000060004&quot; FormType=&quot;2000060004&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Maestro de Vehiculos&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;407&quot; height=&quot;184&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;MSS_MVEH&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;ad [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string MVehiculo {
            get {
                return ResourceManager.GetString("MVehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MSS_DISTRIBUCION.
        /// </summary>
        internal static string NombreAddon {
            get {
                return ResourceManager.GetString("NombreAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Reportes de Eficiencia de Camiones&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;579&quot; height=&quot;400&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;RECC&quot;&gt;
        ///              &lt;Columns /&gt;
        ///      [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string RECCons {
            get {
                return ResourceManager.GetString("RECCons", resourceCulture);
            }
        }
    }
}
